vich_uploader:
    db_driver: orm

    mappings:
        movies_images:
            uri_prefix: '%path_movies_images%'
            upload_destination: '%kernel.project_dir%/public%path_movies_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        series_images:
            uri_prefix: '%path_series_images%'
            upload_destination: '%kernel.project_dir%/public%path_series_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        episodes_images:
            uri_prefix: '%path_episodes_images%'
            upload_destination: '%kernel.project_dir%/public%path_episodes_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        movies_videos:
            uri_prefix: '%path_movies_videos%'
            upload_destination: '%kernel.project_dir%/public%path_movies_videos%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        episodes_videos:
            uri_prefix: '%path_episodes_videos%'
            upload_destination: '%kernel.project_dir%/public%path_episodes_videos%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer